/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import reportes.ReporteVentaVendedorForm;

/**
 *
 * @author Jorge Ccallo M
 */
public class PrincipalForm extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalForm
     */
    public PrincipalForm() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/img/store-icon.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ventanaPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuSalir = new javax.swing.JMenu();
        menuAyuda = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuGenerarVenta = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuCliente = new javax.swing.JMenuItem();
        menuVendedor = new javax.swing.JMenuItem();
        menuProducto = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        menuReporteVentaVendedor = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Venta");
        setExtendedState(6);

        javax.swing.GroupLayout ventanaPrincipalLayout = new javax.swing.GroupLayout(ventanaPrincipal);
        ventanaPrincipal.setLayout(ventanaPrincipalLayout);
        ventanaPrincipalLayout.setHorizontalGroup(
            ventanaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        ventanaPrincipalLayout.setVerticalGroup(
            ventanaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 245, Short.MAX_VALUE)
        );

        menuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu.png"))); // NOI18N
        menuSalir.setText("Menu");
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });

        menuAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/help-item.png"))); // NOI18N
        menuAyuda.setText("Ayuda");
        menuAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAyudaActionPerformed(evt);
            }
        });
        menuSalir.add(menuAyuda);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout-item.png"))); // NOI18N
        jMenuItem2.setText("Salir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        menuSalir.add(jMenuItem2);

        jMenuBar1.add(menuSalir);

        menuGenerarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/venta.png"))); // NOI18N
        menuGenerarVenta.setText("Ventas");
        menuGenerarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGenerarVentaActionPerformed(evt);
            }
        });

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sale-item.png"))); // NOI18N
        jMenuItem1.setText("Generar venta");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGenerarVentaActionPerformed(evt);
            }
        });
        menuGenerarVenta.add(jMenuItem1);

        jMenuBar1.add(menuGenerarVenta);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mantenimiento.png"))); // NOI18N
        jMenu3.setText("Mantenimientos");

        menuCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cliente-item.png"))); // NOI18N
        menuCliente.setText("Clientes");
        menuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClienteActionPerformed(evt);
            }
        });
        jMenu3.add(menuCliente);

        menuVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/seller-item.png"))); // NOI18N
        menuVendedor.setText("Vendedores");
        menuVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVendedorActionPerformed(evt);
            }
        });
        jMenu3.add(menuVendedor);

        menuProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/product-item.png"))); // NOI18N
        menuProducto.setText("Productos");
        menuProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProductoActionPerformed(evt);
            }
        });
        jMenu3.add(menuProducto);

        jMenuBar1.add(jMenu3);

        menuReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reporte.png"))); // NOI18N
        menuReportes.setText("Reportes");

        menuReporteVentaVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reporte-item.png"))); // NOI18N
        menuReporteVentaVendedor.setText("Reporte Venta Vendedor");
        menuReporteVentaVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReporteVentaVendedorActionPerformed(evt);
            }
        });
        menuReportes.add(menuReporteVentaVendedor);

        jMenuBar1.add(menuReportes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ventanaPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ventanaPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void centrarVentana(JInternalFrame frame) {
        ventanaPrincipal.add(frame);
        Dimension dPrincipalFrame = ventanaPrincipal.getSize();
        Dimension dInternoFrame = frame.getSize();
        int x = (dPrincipalFrame.width - dInternoFrame.width) / 2;
        int y = (dPrincipalFrame.height - dInternoFrame.height) / 2;
        frame.setLocation(x, y);
        frame.setVisible(true);
    }
    
    private void menuAyuda() {
        JOptionPane.showMessageDialog(this, "Sistema de Venta Total Look.\nsupport@totallook.com"); 
    }

    private void menuAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAyudaActionPerformed
        menuAyuda();
    }//GEN-LAST:event_menuAyudaActionPerformed

    private void menuGenerarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGenerarVentaActionPerformed
        VentaForm ventaForm = new VentaForm();
        centrarVentana(ventaForm);
    }//GEN-LAST:event_menuGenerarVentaActionPerformed

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuSalirActionPerformed

    private void menuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClienteActionPerformed
        ClienteForm clienteForm = new ClienteForm();
        centrarVentana(clienteForm);
    }//GEN-LAST:event_menuClienteActionPerformed

    private void menuProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProductoActionPerformed
        ProductoForm productoForm = new ProductoForm();
        centrarVentana(productoForm);
    }//GEN-LAST:event_menuProductoActionPerformed

    private void menuVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVendedorActionPerformed
        VendedorForm vendedorForm = new VendedorForm();
        centrarVentana(vendedorForm);
    }//GEN-LAST:event_menuVendedorActionPerformed

    private void menuReporteVentaVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReporteVentaVendedorActionPerformed
        ReporteVentaVendedorForm reporteVentaVendedorForm = new ReporteVentaVendedorForm();
        centrarVentana(reporteVentaVendedorForm);
    }//GEN-LAST:event_menuReporteVentaVendedorActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem menuAyuda;
    private javax.swing.JMenuItem menuCliente;
    private javax.swing.JMenu menuGenerarVenta;
    private javax.swing.JMenuItem menuProducto;
    private javax.swing.JMenuItem menuReporteVentaVendedor;
    private javax.swing.JMenu menuReportes;
    private javax.swing.JMenu menuSalir;
    private javax.swing.JMenuItem menuVendedor;
    public static javax.swing.JDesktopPane ventanaPrincipal;
    // End of variables declaration//GEN-END:variables
}
